version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: deploy/Dockerfile.frontend
    container_name: frontend
    volumes:
      - ./dist:/app/dist
    environment:
      - VITE_API_BASE_URL=/api
      - VITE_BASE_PATH=/
    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: deploy/Dockerfile.backend
    container_name: backend
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=production
      - SECRET_KEY=${SECRET_KEY:-development-secret-key}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY}
    ports:
      - "5000:5000"
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8080:8080"
    volumes:
      - ./dist:/app/dist
      - ./deploy/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

  # Local Supabase database (PostgreSQL)
  supabase-db:
    image: supabase/postgres:14.1.0.21
    ports:
      - "${DB_PORT:-5433}:5432"  # External 5433, internal always 5432
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - supabase-db-data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  supabase-db-data:

networks:
  app-network:
    driver: bridge
