FROM node:18-alpine as builder

WORKDIR /app

# Copy package files
COPY package*.json ./
RUN npm ci

# Copy the rest of the code
COPY . .

# Build the application
RUN npm run build

# Check if build files exist
RUN ls -la dist

# Production stage
FROM nginx:alpine

# Copy built files from builder stage
COPY --from=builder /app/dist /app/dist

# Copy nginx configuration
COPY deploy/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 8080

CMD ["nginx", "-g", "daemon off;"]
